# See stimuli from the original dataset

In [40]:
import altair as alt 
import pandas as pd 
import polars as pl

## Experiment 1

- “the bias of three mark types: 1) points equally spaced along the x-axis, or Cartesian spaced, 2) points equally spaced along the arc of the line, and 3) a line.”
- “We created stimuli that included more variability in the higher y-values and then reflected the stimuli to create graphs with more variability in the lower y-values (see Figure 2).” -> this explains the `flip` column in the dataset
- “We used a 2 (variability upper vs. lower `flip`) × 2 (more vs. less variability `noise`?) within-subjects design for a total of 4 stimuli types of interest.”
- Used 12 seeds $\times$ 4 stimuli -> 48 stimuli data set ...?

In [26]:
df_1 = pl.read_json("../../data/moritz/stimuli/exp1-stimuli.json")
df_1

shape: (48, 8)
┌───────┬──────┬─────────────┬───────┬──────┬──────────────────┬─────────────────┬─────────────────┐
│ index ┆ seed ┆ noise       ┆ flip  ┆ type ┆ data             ┆ lineData        ┆ highNoiseData   │
│ ---   ┆ ---  ┆ ---         ┆ ---   ┆ ---  ┆ ---              ┆ ---             ┆ ---             │
│ i64   ┆ i64  ┆ list[f64]   ┆ bool  ┆ str  ┆ list[struct[2]]  ┆ list[struct[2]] ┆ list[struct[2]] │
╞═══════╪══════╪═════════════╪═══════╪══════╪══════════════════╪═════════════════╪═════════════════╡
│ 0     ┆ 1    ┆ [0.0, 0.15] ┆ false ┆ line ┆ [{0,0.836738},   ┆ [{0,0.836738},  ┆ [{0,0.812146},  │
│       ┆      ┆             ┆       ┆      ┆ {1,0.846661}, …… ┆ {1,0.846661},   ┆ {1,0.872021},   │
│       ┆      ┆             ┆       ┆      ┆                  ┆ ……              ┆ ……              │
│ 1     ┆ 1    ┆ [0.0, 0.15] ┆ true  ┆ line ┆ [{0,0.163262},   ┆ [{0,0.163262},  ┆ [{0,0.187854},  │
│       ┆      ┆             ┆       ┆      ┆ {1,0.153339}, …… ┆ {1,0.153339},   ┆ {1,0.127979},   │
│       ┆      ┆             ┆       ┆      ┆                  ┆ ……              ┆ ……              │
│ 2     ┆ 1    ┆ [0.0, 0.4]  ┆ false ┆ line ┆ [{0,0.812146},   ┆ [{0,0.812146},  ┆ [{0,0.812146},  │
│       ┆      ┆             ┆       ┆      ┆ {1,0.872021}, …… ┆ {1,0.872021},   ┆ {1,0.872021},   │
│       ┆      ┆             ┆       ┆      ┆                  ┆ ……              ┆ ……              │
│ 3     ┆ 1    ┆ [0.0, 0.4]  ┆ true  ┆ line ┆ [{0,0.187854},   ┆ [{0,0.187854},  ┆ [{0,0.187854},  │
│       ┆      ┆             ┆       ┆      ┆ {1,0.127979}, …… ┆ {1,0.127979},   ┆ {1,0.127979},   │
│       ┆      ┆             ┆       ┆      ┆                  ┆ ……              ┆ ……              │
│ 4     ┆ 2    ┆ [0.0, 0.15] ┆ false ┆ line ┆ [{0,0.817333},   ┆ [{0,0.817333},  ┆ [{0,0.871047},  │
│       ┆      ┆             ┆       ┆      ┆ {1,0.800974}, …… ┆ {1,0.800974},   ┆ {1,0.826411},   │
│       ┆      ┆             ┆       ┆      ┆                  ┆ ……              ┆ ……              │
│ …     ┆ …    ┆ …           ┆ …     ┆ …    ┆ …                ┆ …               ┆ …               │
│ 43    ┆ 11   ┆ [0.0, 0.4]  ┆ true  ┆ line ┆ [{0,0.814328},   ┆ [{0,0.814328},  ┆ [{0,0.814328},  │
│       ┆      ┆             ┆       ┆      ┆ {1,0.73583}, … … ┆ {1,0.73583}, …  ┆ {1,0.73583}, …  │
│       ┆      ┆             ┆       ┆      ┆                  ┆ …               ┆ …               │
│ 44    ┆ 19   ┆ [0.0, 0.15] ┆ false ┆ line ┆ [{0,0.920993},   ┆ [{0,0.920993},  ┆ [{0,1.0},       │
│       ┆      ┆             ┆       ┆      ┆ {1,0.873257}, …… ┆ {1,0.873257},   ┆ {1,0.971583}, … │
│       ┆      ┆             ┆       ┆      ┆                  ┆ ……              ┆ {119…           │
│ 45    ┆ 19   ┆ [0.0, 0.15] ┆ true  ┆ line ┆ [{0,0.079007},   ┆ [{0,0.079007},  ┆ [{0,0.0},       │
│       ┆      ┆             ┆       ┆      ┆ {1,0.126743}, …… ┆ {1,0.126743},   ┆ {1,0.028417}, … │
│       ┆      ┆             ┆       ┆      ┆                  ┆ ……              ┆ {119…           │
│ 46    ┆ 19   ┆ [0.0, 0.4]  ┆ false ┆ line ┆ [{0,1.0},        ┆ [{0,1.0},       ┆ [{0,1.0},       │
│       ┆      ┆             ┆       ┆      ┆ {1,0.971583}, …  ┆ {1,0.971583}, … ┆ {1,0.971583}, … │
│       ┆      ┆             ┆       ┆      ┆ {119…            ┆ {119…           ┆ {119…           │
│ 47    ┆ 19   ┆ [0.0, 0.4]  ┆ true  ┆ line ┆ [{0,0.0},        ┆ [{0,0.0},       ┆ [{0,0.0},       │
│       ┆      ┆             ┆       ┆      ┆ {1,0.028417}, …  ┆ {1,0.028417}, … ┆ {1,0.028417}, … │
│       ┆      ┆             ┆       ┆      ┆ {119…            ┆ {119…           ┆ {119…           │
└───────┴──────┴─────────────┴───────┴──────┴──────────────────┴─────────────────┴─────────────────┘

In [28]:
df_1.describe()

shape: (9, 9)
┌────────────┬───────┬───────────┬───────┬───┬──────┬──────┬──────────┬───────────────┐
│ statistic  ┆ index ┆ seed      ┆ noise ┆ … ┆ type ┆ data ┆ lineData ┆ highNoiseData │
│ ---        ┆ ---   ┆ ---       ┆ ---   ┆   ┆ ---  ┆ ---  ┆ ---      ┆ ---           │
│ str        ┆ f64   ┆ f64       ┆ f64   ┆   ┆ str  ┆ f64  ┆ f64      ┆ f64           │
╞════════════╪═══════╪═══════════╪═══════╪═══╪══════╪══════╪══════════╪═══════════════╡
│ count      ┆ 48.0  ┆ 48.0      ┆ 48.0  ┆ … ┆ 48   ┆ 48.0 ┆ 48.0     ┆ 48.0          │
│ null_count ┆ 0.0   ┆ 0.0       ┆ 0.0   ┆ … ┆ 0    ┆ 0.0  ┆ 0.0      ┆ 0.0           │
│ mean       ┆ 23.5  ┆ 11.416667 ┆ null  ┆ … ┆ null ┆ null ┆ null     ┆ null          │
│ std        ┆ 14.0  ┆ 6.222243  ┆ null  ┆ … ┆ null ┆ null ┆ null     ┆ null          │
│ min        ┆ 0.0   ┆ 1.0       ┆ null  ┆ … ┆ line ┆ null ┆ null     ┆ null          │
│ 25%        ┆ 12.0  ┆ 8.0       ┆ null  ┆ … ┆ null ┆ null ┆ null     ┆ null          │
│ 50%        ┆ 24.0  ┆ 14.0      ┆ null  ┆ … ┆ null ┆ null ┆ null     ┆ null          │
│ 75%        ┆ 35.0  ┆ 16.0      ┆ null  ┆ … ┆ null ┆ null ┆ null     ┆ null          │
│ max        ┆ 47.0  ┆ 19.0      ┆ null  ┆ … ┆ line ┆ null ┆ null     ┆ null          │
└────────────┴───────┴───────────┴───────┴───┴──────┴──────┴──────────┴───────────────┘

In [30]:
df_1.select(pl.col('noise').value_counts())

shape: (2, 1)
┌──────────────────┐
│ noise            │
│ ---              │
│ struct[2]        │
╞══════════════════╡
│ {[0.0, 0.15],24} │
│ {[0.0, 0.4],24}  │
└──────────────────┘

In [32]:
df_1.select(pl.col('flip').value_counts())

shape: (2, 1)
┌────────────┐
│ flip       │
│ ---        │
│ struct[2]  │
╞════════════╡
│ {true,24}  │
│ {false,24} │
└────────────┘

In [34]:
df_1.select(pl.col('seed').value_counts())

shape: (12, 1)
┌───────────┐
│ seed      │
│ ---       │
│ struct[2] │
╞═══════════╡
│ {14,4}    │
│ {18,4}    │
│ {13,4}    │
│ {19,4}    │
│ {2,4}     │
│ …         │
│ {1,4}     │
│ {3,4}     │
│ {16,4}    │
│ {17,4}    │
│ {8,4}     │
└───────────┘

In [35]:
df_1 = pd.read_json("../../data/moritz/stimuli/exp1-stimuli.json")
df_1.head(5)

,index,seed,noise,flip,type,data,lineData,highNoiseData
0,0,1,"[0, 0.15]",False,line,"[{'x': 0, 'y': 0.8367378859167081}, {'x': 1, '...","[{'x': 0, 'y': 0.8367378859167081}, {'x': 1, '...","[{'x': 0, 'y': 0.8121457281461191}, {'x': 1, '..."
1,1,1,"[0, 0.15]",True,line,"[{'x': 0, 'y': 0.16326211408329}, {'x': 1, 'y'...","[{'x': 0, 'y': 0.16326211408329}, {'x': 1, 'y'...","[{'x': 0, 'y': 0.18785427185388}, {'x': 1, 'y'..."
2,2,1,"[0, 0.4]",False,line,"[{'x': 0, 'y': 0.8121457281461191}, {'x': 1, '...","[{'x': 0, 'y': 0.8121457281461191}, {'x': 1, '...","[{'x': 0, 'y': 0.8121457281461191}, {'x': 1, '..."
3,3,1,"[0, 0.4]",True,line,"[{'x': 0, 'y': 0.18785427185388}, {'x': 1, 'y'...","[{'x': 0, 'y': 0.18785427185388}, {'x': 1, 'y'...","[{'x': 0, 'y': 0.18785427185388}, {'x': 1, 'y'..."
4,4,2,"[0, 0.15]",False,line,"[{'x': 0, 'y': 0.8173330159781991}, {'x': 1, '...","[{'x': 0, 'y': 0.8173330159781991}, {'x': 1, '...","[{'x': 0, 'y': 0.871046783246998}, {'x': 1, 'y..."

In [39]:
df_1.value_counts(["noise", "flip"])

TypeError: unhashable type: 'list'

In [10]:
# define a function that generates things 
from typing import Literal 

SimulationType = ["data", "lineData", "highNoiseData"]
PlotType = ["point", "line"]

def plot(row: int, plot_type: PlotType, col: SimulationType): 
    row_df = df_1.iloc[row]
    plot_df = pd.DataFrame(row_df[col])
    if plot_type == "point": 
        p = alt.Chart(plot_df).mark_point(filled=True).encode(
            x=alt.X("x", axis=None),
            y=alt.Y("y", axis=None).scale(domain=[0, 1])
        ).properties(
            width=500,
            height=200
        )
    elif plot_type == "line":
        p = alt.Chart(plot_df).mark_line().encode(
            x=alt.X("x", axis=None),
            y=alt.Y("y", axis=None).scale(domain=[0, 1])
        ).properties(
            width=500,
            height=200
        )
    return p

In [23]:
plot(0, "line", "data")

AttributeError: 'DataFrame' object has no attribute 'iloc'

In [12]:
plot(1, "line", "data")

alt.Chart(...)

In [13]:
plot(0, "point", "data")

alt.Chart(...)

In [14]:
plot(0, "line", "lineData")

alt.Chart(...)

In [15]:
plot(0, "line", "highNoiseData")

alt.Chart(...)

In [16]:
plot(1, "line", "highNoiseData")

alt.Chart(...)

In [17]:
plot(1, "point", "highNoiseData")

alt.Chart(...)

Somehow this is making me think about gradience and the judgment of variance / mean ...

## Experiment 2

In [56]:
df_2 = pd.read_json("../../data/moritz/stimuli/exp2-stimuli.json")
df_2.head(5)

,index,seed,noise,flip,type,data,lineData,highNoiseData
0,0,1,"[0, 0]",False,line,"[{'x': 0, 'y': 0.830302703203718}, {'x': 2, 'y...","[{'x': 0, 'y': 0.830302703203718}, {'x': 2, 'y...","[{'x': 0, 'y': 0.8121457281461191}, {'x': 2, '..."
1,1,1,"[0, 0]",True,line,"[{'x': 0, 'y': 0.16969729679628}, {'x': 2, 'y'...","[{'x': 0, 'y': 0.16969729679628}, {'x': 2, 'y'...","[{'x': 0, 'y': 0.18785427185388}, {'x': 2, 'y'..."
2,2,1,"[0, 0.4]",False,line,"[{'x': 0, 'y': 0.8121457281461191}, {'x': 2, '...","[{'x': 0, 'y': 0.8121457281461191}, {'x': 2, '...","[{'x': 0, 'y': 0.8121457281461191}, {'x': 2, '..."
3,3,1,"[0, 0.4]",True,line,"[{'x': 0, 'y': 0.18785427185388}, {'x': 2, 'y'...","[{'x': 0, 'y': 0.18785427185388}, {'x': 2, 'y'...","[{'x': 0, 'y': 0.18785427185388}, {'x': 2, 'y'..."
4,4,1,"[0, 0]",False,point,"[{'x': 0, 'y': 0.830302703203718}, {'x': 2, 'y...","[{'x': 0, 'y': 0.830302703203718}, {'x': 2, 'y...","[{'x': 0, 'y': 0.8121457281461191}, {'x': 2, '..."