# Analyzing data from Task 1

Note to self: trying to run `cmdstanpy` on windows is quite painful ...

In [1]:
import polars as pl
import pandas as pd
import pymc as pm
import arviz as az
import arviz_plots as azp

In [2]:
# read in data 
task1_df = pl.read_csv("../data/processed/task1.csv")
task1_df.head()

shape: (5, 27)
┌─────┬──────────────────────────┬───────┬─────┬───┬───────────┬─────────────┬──────────┬──────────┐
│     ┆ participantId            ┆ task  ┆ id  ┆ … ┆ phy.mod.x ┆ va.select.x ┆ va.med.x ┆ va.mod.x │
│ --- ┆ ---                      ┆ ---   ┆ --- ┆   ┆ ---       ┆ ---         ┆ ---      ┆ ---      │
│ i64 ┆ str                      ┆ str   ┆ i64 ┆   ┆ f64       ┆ f64         ┆ f64      ┆ f64      │
╞═════╪══════════════════════════╪═══════╪═════╪═══╪═══════════╪═════════════╪══════════╪══════════╡
│ 1   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 1   ┆ … ┆ 62.920652 ┆ 5.321116    ┆ 5.368009 ┆ 5.390766 │
│ 2   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 2   ┆ … ┆ 50.592391 ┆ 5.072333    ┆ 5.171459 ┆ 4.335665 │
│ 3   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 3   ┆ … ┆ 63.036957 ┆ 5.321116    ┆ 5.257493 ┆ 5.400716 │
│ 4   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 4   ┆ … ┆ 47.801087 ┆ 5.072333    ┆ 5.165791 ┆ 4.096666 │
│ 5   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 5   ┆ … ┆ 53.848913 ┆ 4.554715    ┆ 4.496682 ┆ 4.61445  │
└─────┴──────────────────────────┴───────┴─────┴───┴───────────┴─────────────┴──────────┴──────────┘

# Comiple the stan model 

... using the `stan` file. 

Following guide [here](https://mc-stan.org/cmdstanpy/users-guide/workflow.html).

In [5]:
#from plotly import data
# data_file = {"N": 10, "y": [0,1,0,0,0,0,0,0,0,1]}
t_file = os.path.join(os.getcwd(), "bernoulli.stan.json" )
t_file

'/Users/shenglong/Downloads/vis-decode-analysis/PyMC/bernoulli.stan.json'

In [7]:
fit = model.sample(data=t_file)

13:31:48 - cmdstanpy - INFO - CmdStan start processing

chain 1:   0%|          | 0/2000 [00:00<?, ?it/s, (Warmup)]

chain 2:   0%|          | 0/2000 [00:00<?, ?it/s, (Warmup)]

chain 3:   0%|          | 0/2000 [00:00<?, ?it/s, (Warmup)]

chain 4:   0%|          | 0/2000 [00:00<?, ?it/s, (Warmup)]

13:31:48 - cmdstanpy - INFO - CmdStan done processing.

In [8]:
fit.draws_pd()

,chain__,iter__,draw__,lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,divergent__,energy__,theta
0,1.0,1.0,1.0,-6.993194,0.623146,1.221775,2.0,3.0,0.0,9.057578,0.343499
1,1.0,2.0,2.0,-6.775082,0.906860,1.221775,2.0,3.0,0.0,7.176191,0.279803
2,1.0,3.0,3.0,-7.395879,0.728540,1.221775,1.0,1.0,0.0,7.412702,0.406487
3,1.0,4.0,4.0,-7.214523,1.000000,1.221775,2.0,3.0,0.0,7.322613,0.143871
4,1.0,5.0,5.0,-7.448529,0.972227,1.221775,2.0,3.0,0.0,7.969621,0.124389
...,...,...,...,...,...,...,...,...,...,...,...
3995,4.0,996.0,3996.0,-8.683474,0.906990,0.964482,1.0,1.0,0.0,8.695204,0.068439
3996,4.0,997.0,3997.0,-7.932809,1.000000,0.964482,1.0,1.0,0.0,8.624037,0.096270
3997,4.0,998.0,3998.0,-6.892504,0.997005,0.964482,1.0,3.0,0.0,7.830895,0.187132
3998,4.0,999.0,3999.0,-6.749703,0.904827,0.964482,2.0,3.0,0.0,7.568724,0.257295
3999,4.0,1000.0,4000.0,-6.779014,0.995544,0.964482,2.0,3.0,0.0,6.782294,0.219773

In [9]:
# connect to arviz 
import arviz as az

cmdstanpy_data = az.from_cmdstanpy(posterior=fit)
cmdstanpy_data

Inference data with groups:
	> posterior
	> sample_stats

## Testing with our own models

In [ ]:
task1_stanfile = os.path.join('../analysis/final/stan_files/', "task1.weighted.avg.stan")
task1_model = CmdStanModel(stan_file=task1_stanfile)

13:33:55 - cmdstanpy - INFO - compiling stan file /Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.weighted.avg.stan to exe file /Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.weighted.avg
13:34:10 - cmdstanpy - INFO - compiled model executable: /Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.weighted.avg

In [12]:
task1_model.name

'task1.weighted.avg'

In [13]:
task1_model.stan_file

'/Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.weighted.avg.stan'

In [14]:
task1_model.exe_file

'/Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.weighted.avg'

In [15]:
task1_model.code()

'data {\n  int<lower=1> N;   // total number of observations\n  int<lower=1> J;   // total number of participants \n  array[N] int<lower=1, upper=J> id; // participant ID for each observation \n  vector[N] x;      // observed values\n  vector[N] x_med;  // known median values\n  vector[N] x_mod;  // known mode values\n}\n\nparameters {\n  // Population-level parameters \n  real mu_mod_mean;\n  real<lower=0> mu_mod_sd; \n  real mu_med_mean;\n  real<lower=0> mu_med_sd; \n  \n  // standard deviations for x_med and x_mod\n  real log_sigma_mod_mean; \n  real<lower=0> log_sigma_mod_sd; \n  real log_sigma_med_mean; \n  real<lower=0> log_sigma_med_sd;\n\n  // Particiipant-level parameters\n  vector[J] mu_mod; \n  vector<lower=0>[J] sigma_mod; \n  vector[J] mu_med; \n  vector<lower=0>[J] sigma_med; \n}\n\ntransformed parameters {\n  vector<lower=0, upper=1>[N] theta; // weight \n  vector[N] inv_mse_med;\n  vector[N] inv_mse_mod;  \n\n  for (n in 1:N) {\n    int j = id[n]; \n    inv_mse_med[n] = 1 / (square(mu_med[j]) + square(sigma_med[j])); \n    inv_mse_mod[n] = 1 / (square(x_mod[n] - x_med[n] + mu_mod[j]) + square(sigma_mod[j])); \n\n    theta[n] = inv_mse_med[n] / (inv_mse_med[n] + inv_mse_mod[n]); \n  }\n}\n\nmodel {\n  // priors\n  mu_mod_mean ~ normal(0.01, 0.02); \n  mu_mod_sd ~ normal(0.04, 0.03); \n  log_sigma_mod_mean ~ normal(-1.37, 0.10); \n  log_sigma_mod_sd ~ normal(0.34, 0.10); \n\n  mu_med_mean ~ normal(0, 1); \n  mu_med_sd ~ normal(0, 1); \n  log_sigma_med_mean ~ normal(0, 1); \n  log_sigma_med_sd ~ normal(0, 1); \n\n  for (j in 1:J){\n    mu_mod[j] ~ normal(mu_mod_mean, mu_mod_sd);\n    sigma_mod[j] ~ lognormal(log_sigma_mod_mean, log_sigma_mod_sd); \n    mu_med[j] ~ normal(mu_med_mean, mu_med_sd); \n    sigma_med[j] ~ lognormal(log_sigma_med_mean, log_sigma_med_sd); \n  }\n\n  // likelihood\n  for (n in 1:N) {\n    int j = id[n]; \n    target += normal_lpdf(x[n] | theta[n] * (x_med[n] + mu_med[j]) + (1 - theta[n]) * (x_mod[n] + mu_mod[j]),\n                                 sqrt(square(theta[n]) * square(sigma_med[j]) + square(1 - theta[n]) * square(sigma_mod[j]))); \n  }\n}\ngenerated quantities {\n  vector[N] log_lik; \n  vector[N] y_rep; // posterior predictive checks\n  vector[N] x_org = x;\n  \n  for (n in 1:N) {\n    int j = id[n]; \n    log_lik[n] = normal_lpdf(x[n] | theta[n] * (x_med[n] + mu_med[j]) + (1 - theta[n]) * (x_mod[n] + mu_mod[j]),\n                                 sqrt(square(theta[n]) * square(sigma_med[j]) + square(1 - theta[n]) * square(sigma_mod[j])));  \n\n\n    y_rep[n] = normal_rng(theta[n] * (x_med[n] + mu_med[j]) + (1 - theta[n]) * (x_mod[n] + mu_mod[j]),\n                                 sqrt(square(theta[n]) * square(sigma_med[j]) + square(1 - theta[n]) * square(sigma_mod[j])));  \n\n  }\n}\n'

In [16]:
# prepare data for stan model 
# task1_df

In [4]:
# fit the model 
# TODO 

# fit = task1_model.sample()

In [ ]:
# Translate to InferenceData 

# task1_idata = az.from_cmdstanpy(fit)