# Analyzing data from Task 1

Note to self: trying to run `cmdstanpy` on windows is quite painful ...

In [1]:
import polars as pl
import pandas as pd
import pymc as pm
import arviz as az
import arviz_plots as azp

In [3]:
# read in data 
task1_df = pl.read_csv("../data/processed/task1.csv")
task1_df.head()

shape: (5, 27)
┌─────┬──────────────────────────┬───────┬─────┬───┬───────────┬─────────────┬──────────┬──────────┐
│     ┆ participantId            ┆ task  ┆ id  ┆ … ┆ phy.mod.x ┆ va.select.x ┆ va.med.x ┆ va.mod.x │
│ --- ┆ ---                      ┆ ---   ┆ --- ┆   ┆ ---       ┆ ---         ┆ ---      ┆ ---      │
│ i64 ┆ str                      ┆ str   ┆ i64 ┆   ┆ f64       ┆ f64         ┆ f64      ┆ f64      │
╞═════╪══════════════════════════╪═══════╪═════╪═══╪═══════════╪═════════════╪══════════╪══════════╡
│ 1   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 1   ┆ … ┆ 62.920652 ┆ 5.321116    ┆ 5.368009 ┆ 5.390766 │
│ 2   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 2   ┆ … ┆ 50.592391 ┆ 5.072333    ┆ 5.171459 ┆ 4.335665 │
│ 3   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 3   ┆ … ┆ 63.036957 ┆ 5.321116    ┆ 5.257493 ┆ 5.400716 │
│ 4   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 4   ┆ … ┆ 47.801087 ┆ 5.072333    ┆ 5.165791 ┆ 4.096666 │
│ 5   ┆ 67f03733938aa3f0d17ce8a8 ┆ task1 ┆ 5   ┆ … ┆ 53.848913 ┆ 4.554715    ┆ 4.496682 ┆ 4.61445  │
└─────┴──────────────────────────┴───────┴─────┴───┴───────────┴─────────────┴──────────┴──────────┘

# Comiple the stan model 

... using the `stan` file. 

Following guide [here](https://mc-stan.org/cmdstanpy/users-guide/workflow.html).

In [7]:
import cmdstanpy 
# cmdstanpy.install_cmdstan() # compiler=True is only valid on windows 
from cmdstanpy import cmdstan_path
print(f'cmdstan is installed at {cmdstan_path()}')

cmdstan is installed at /Users/shenglong/.cmdstan/cmdstan-2.38.0

In [8]:
# test to see that cmdstanpy is installed correctly ... 
import os 
from cmdstanpy import CmdStanModel

stan_file = os.path.join(os.getcwd(), "bernoulli.stan")
model = CmdStanModel(stan_file = stan_file)
# inpsect model object 
print(model)
# inspect compiledm odel 
print(model.exe_info())

CmdStanModel: name=bernoulli
	 stan_file=/Users/shenglong/Downloads/vis-decode-analysis/PyMC/bernoulli.stan
	 exe_file=/Users/shenglong/Downloads/vis-decode-analysis/PyMC/bernoulli
	 compiler_options=stanc_options={}, cpp_options={}
{'stan_version_major': '2', 'stan_version_minor': '38', 'stan_version_patch': '0', 'STAN_THREADS': 'false', 'STAN_MPI': 'false', 'STAN_OPENCL': 'false', 'STAN_NO_RANGE_CHECKS': 'false'}

In [9]:
#from plotly import data
# data_file = {"N": 10, "y": [0,1,0,0,0,0,0,0,0,1]}
t_file = os.path.join(os.getcwd(), "bernoulli.stan.json" )
t_file

'/Users/shenglong/Downloads/vis-decode-analysis/PyMC/bernoulli.stan.json'

In [10]:
fit = model.sample(data=t_file)

18:16:52 - cmdstanpy - INFO - CmdStan start processing
chain 1:   0%|          | 0/2000 [00:00<?, ?it/s, (Warmup)]


chain 1:  50%|█████     | 1000/2000 [00:00<00:00, 50032.85it/s, (Sampling)]


chain 1: 100%|██████████| 2000/2000 [00:00<00:00, 79785.88it/s, (Sampling completed)]
chain 2: 100%|██████████| 2000/2000 [00:00<00:00, 79840.56it/s, (Sampling completed)]

chain 3: 100%|██████████| 2000/2000 [00:00<00:00, 81119.89it/s, (Sampling completed)]


chain 4: 100%|██████████| 2000/2000 [00:00<00:00, 82121.29it/s, (Sampling completed)]

18:16:52 - cmdstanpy - INFO - CmdStan done processing.

In [11]:
fit.draws_pd()

,chain__,iter__,draw__,lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,divergent__,energy__,theta
0,1.0,1.0,1.0,-6.863713,0.997550,0.852296,2.0,3.0,0.0,7.398634,0.193312
1,1.0,2.0,2.0,-6.874313,0.999440,0.852296,2.0,7.0,0.0,6.874526,0.316027
2,1.0,3.0,3.0,-6.749434,1.000000,0.852296,2.0,3.0,0.0,6.876561,0.256683
3,1.0,4.0,4.0,-6.785219,0.989479,0.852296,1.0,3.0,0.0,6.814822,0.216982
4,1.0,5.0,5.0,-7.323959,0.955326,0.852296,2.0,3.0,0.0,7.337468,0.396994
...,...,...,...,...,...,...,...,...,...,...,...
3995,4.0,996.0,3996.0,-6.748022,1.000000,0.927030,2.0,3.0,0.0,7.582353,0.249866
3996,4.0,997.0,3997.0,-7.146863,0.902348,0.927030,1.0,3.0,0.0,7.344228,0.150766
3997,4.0,998.0,3998.0,-7.126407,1.000000,0.927030,1.0,1.0,0.0,7.203674,0.153004
3998,4.0,999.0,3999.0,-7.602354,0.963077,0.927030,2.0,7.0,0.0,7.651814,0.431286
3999,4.0,1000.0,4000.0,-7.383884,0.662080,0.927030,1.0,3.0,0.0,9.679460,0.129230

In [12]:
# connect to arviz 
import arviz as az

cmdstanpy_data = az.from_cmdstanpy(posterior=fit)
cmdstanpy_data

Inference data with groups:
	> posterior
	> sample_stats

In [8]:
import os 
from cmdstanpy import CmdStanModel

import logging

# Enable verbose logging
logging.getLogger('cmdstanpy').setLevel(logging.DEBUG)

task1_stanfile = os.path.join('../analysis/final/stan_files/', "task1.mix.stan")
task1_model = CmdStanModel(stan_file=task1_stanfile)

14:31:37 - cmdstanpy - INFO - compiling stan file /Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.mix.stan to exe file /Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.mix

ValueError: Failed to compile Stan model '/Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.mix.stan'. Console:

--- Translating Stan model to C++ code ---
bin/stanc --filename-in-msg=task1.mix.stan --o=/Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.mix.hpp /Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.mix.stan
Syntax error in 'task1.mix.stan', line 4, column 27 to column 28, parsing error:
   -------------------------------------------------
     2:    int<lower=1> N;              // total number of observations
     3:    int<lower=1> J;              // number of participants
     4:    int<lower=1, upper=J> id[N]; // participant ID for each observation
                                    ^
     5:    vector[N] x;                 // observed values
     6:    vector[N] x_med;             // known median values
   -------------------------------------------------

Ill-formed declaration. ";" expected after variable declaration.
It looks like you are trying to use the old array syntax.
Please use the new syntax:
array[N] int<lower=1, upper=J> id;
make: *** [/Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.mix.hpp] Error 1

Command ['make', 'STANCFLAGS+=--filename-in-msg=task1.mix.stan', '/Users/shenglong/Downloads/vis-decode-analysis/analysis/final/stan_files/task1.mix']
	exited with code '2' No such file or directory

In [8]:
# task1_model.name
# task1_model.stan_file
# task1_model.exe_file
print(task1_model.code())

NameError: name 'task1_model' is not defined

In [5]:
# prepare data for stan model 


task1_df

NameError: name 'task1_df' is not defined

In [4]:
# fit the model 
# TODO 

# fit = task1_model.sample()

In [ ]:
# Translate to InferenceData 

# task1_idata = az.from_cmdstanpy(fit)